version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      ENVIRONMENT: production
      PORT: 4000
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgrespw
      DATABASE_NAME: arquitectura-web
      JWT_SECRET: 
    depends_on:
      - postgres
    command: >
      sh -c "npm run typeorm:migration:run &&
             npm run start:prod"
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: arquitectura-web
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
